import Head from "next/head";
import { Lato } from "next/font/google";
import { Header } from "@/components/Header";
import { Container } from "@/components/Container";
import { EventCard } from "@/components/EventCard";

const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "700"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={lato.className}>
        <Container>
          <Header />
          <h1>Under Construction</h1>
          <EventCard thumbnailUrl="https://secure.meetupstatic.com/photos/event/9/1/9/3/clean_478597267.jpg" title="Dummy title" eventDate="2023-04-05" eventTime="18:00"/>
        </Container>
      </main>
    </>
  );
}
