import Head from "next/head";
import { Lato } from "next/font/google";
import { Header } from "@/components/Header";

const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "700"],
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={lato.className}>
        <Header />
        <h1>Under Construction</h1>
      </main>
    </>
  );
}
